{% set name = "PyPDF3" %}
{% set version = "1.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PyPDF3-{{ version }}.tar.gz
  sha256: c946f3273419e37258e35e72273f49904ab15723d87a761c1115ef99799f8c5f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - colorama
    - python >={{ python_min }}
    - tqdm >=4.49.0

test:
  imports:
    - PyPDF3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sfneal/PyPDF3
  summary: Pure Python PDF toolkit
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Fork of PyPDF2 with feature improvements.

extra:
  recipe-maintainers:
    - thewchan
